env:
  script:
  - env

lint:
  image: golang:latest
  cache:
    paths:
    - bin
  variables:
    PACKAGE_NAME: github.com/garsue/sparql
  script:
  - test -e ./bin/gometalinter || curl -L https://git.io/vp6lP | sh
  - PATH=$(pwd)/bin:$PATH
  - mkdir -p /go/src/github.com/garsue
  - ln -s $CI_PROJECT_DIR /go/src/${PACKAGE_NAME}
  - cd /go/src/${PACKAGE_NAME}
  - ./bin/gometalinter ./...


