language: go
go:
  - "1.x"

env:
  global:
    - REVIEWDOG_VERSION="0.9.11"

cache:
  directories:
    - ~/bin

install:
  - test -d ~/bin || mkdir -p ~/bin/
  - export PATH=~/bin/:$PATH
  - test -e ~/bin/goverage || (go get github.com/haya14busa/goverage && mv $GOPATH/bin/goverage ~/bin/)

script:
  - go test -race -cover ./...
  - goverage -coverprofile=coverage.txt ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)